version: '3.8'
services:
  app:
    image: acidmux/beef-xss:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    depends_on:
      - app
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped

